server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8

mybatis-plus:
  type-aliases-package: com.canghai.blog.biz.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    jdbc-type-for-null: null
  global-config:
    banner: false

spring:
  datasource:
    username: learn
    password: canghai2020
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://47.107.174.125:3306/learn?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=Asia/Shanghai
    min-idle: 5
    max-active: 10
    initial-size: 5
    max-wait: 60000
    filters: stat,wall,log4j
